aether/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.BASE_DIR / "static")

base/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.landingPage, name = 'landing-page'),
    path('home/', views.home, name = 'home'),
    path('login/', views.loginUser, name = "login"),
    path('logout/', views.logoutUser, name = "logout"),
    path('register/', views.registerUser, name = "register"),
    path('create/', views.createBlog, name='create-blog'),
    path('read/<str:blogID>/', views.readBlog, name='read-blog'),
    path('like/<str:blogID>/', views.likeBlog, name='like-blog'),
    path('profile/<str:userID>/', views.viewProfile, name='view-profile'),
    path('edit-profile/', views.editProfile, name='edit-profile'),
    path('about-us/', views.aboutUs, name='about-us'),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile


class Blog(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    number_of_likes = models.PositiveIntegerField(default=0)
    number_of_comments = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='blog_images/', blank=True, null=True)
    liked_by = models.ManyToManyField(User, related_name='liked_blogs', blank=True)

    def process_image(self):
        if self.image:
            image = Image.open(self.image)
            if image.mode == 'RGBA':
                image = image.convert('RGB')
            width, height = image.size
            min_side = min(width, height)
            left = (width - min_side) / 2
            top = (height - min_side) / 2
            right = (width + min_side) / 2
            bottom = (height + min_side) / 2
            image = image.crop((left, top, right, bottom))

            image = image.resize((640, 640))

            buffer = BytesIO()
            image.save(buffer, format='JPEG')
            self.image = InMemoryUploadedFile(buffer, 'ImageField', self.image.name, 'image/jpeg', buffer.tell(), None)

    def __str__(self):
        return self.title

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    blog= models.ForeignKey(Blog, on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add = True)

    class Meta:
        ordering = ['-created']
    
    def __str__(self):
        return self.body

base/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Blog,Comment

class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("A user with that email already exists.")
        return email

class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content', 'image']

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        labels = {
            'body': '',
        }

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

base/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from .forms import CustomUserCreationForm
from .forms import CustomUserCreationForm, BlogForm, ProfileEditForm, CommentForm
from .models import Blog, Comment

def landingPage(request):
    blogs = Blog.objects.order_by('-number_of_likes')
    context = {'blogs': blogs}
    return render(request, 'base/landing_page.html', context) 

@login_required(login_url='/login')
def home(request):
    return render(request, 'base/home.html')

def registerUser(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'An error occurred during registration.')
    else:
        form = CustomUserCreationForm()

    context = {'form': form}
    return render(request, 'base/register.html', context)

def loginUser(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        
    context = {'page': page}
    return render(request, 'base/login.html', context)

@login_required(login_url='/login')
def logoutUser(request):
    logout(request)
    return redirect('home')

@login_required(login_url='/login')
def createBlog(request):
    context = {}
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.author = request.user
            blog.save()
            blog.process_image()
            blog.save()
            return redirect('home')
    else:
        form = BlogForm()
        context = {'form': form}
    return render(request, 'base/create_blog.html', context)

@login_required(login_url='/login')
def readBlog(request, blogID):
    blog = get_object_or_404(Blog, id=blogID)
    comments = Comment.objects.filter(blog = blogID)
    comment_form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return redirect('read-blog', blog.id)
    context = {'blog': blog, 'comments':comments, 'commentform': comment_form}
    return render(request, 'base/read_blog.html', context)

@login_required(login_url='/login')
def likeBlog(request, blogID):
    if request.method == 'POST':
        blog = get_object_or_404(Blog, id=blogID)

        if request.user in blog.liked_by.all():
            blog.liked_by.remove(request.user)
            blog.number_of_likes -= 1
        else:
            blog.liked_by.add(request.user)
            blog.number_of_likes += 1

        blog.save()
        return JsonResponse({'likes': blog.number_of_likes})

    return JsonResponse({'error': 'Invalid request'}, status=400)

@login_required
def viewProfile(request, userID):
    user = get_object_or_404(User, pk=userID)
    is_owner = user == request.user
    blogs = Blog.objects.filter(author = userID).order_by('-created_on')
    context = {'user_profile': user, 'is_owner': is_owner, 'blogs':blogs}
    return render(request, 'base/view_profile.html', context)

@login_required
def editProfile(request):
    if request.method == 'POST':
        form = ProfileEditForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('view-profile', userID=request.user.id)
    else:
        form = ProfileEditForm(instance=request.user)
    context = {'form': form}
    return render(request, 'base/edit_profile.html', context)

def aboutUs(request):
    return render(request, 'base/about_us.html')

base/templates/base/about_us.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
  <div class="main-container">
      <h1 class="our-readers-loved-text">ABOUT US</h1>
      <div class="banner-img-container">
          <img class="banner-image" src="{% static 'banner.png' %}">
      </div>
  </div>
{% endblock %}

base/templates/base/create_blog.html
{% extends 'main.html' %}

{% block content %}
  <div class="main-container">
    <h2 class="hello-user-text">CREATE NEW BLOGPOST</h2>
    <div class="form-container">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_title">Title:</label>
        {{ form.title }}

        <label for="id_image">Image:</label>
        {{ form.image }}
       
        <label for="id_content">Content:</label>
        {{ form.content }}        

        <button type="submit">PUBLISH</button>
      </form>
    </div>
  </div>
{% endblock %}

base/templates/base/edit_profile.html
{% extends 'main.html' %}

{% block content %}
    <div class="main-container">
        <h1 class="hello-user-text">EDIT PROFILE</h1>
        <div class="form-container">
        <form method="post" action="">
            {% csrf_token %}

            <label for="id_username">Username</label>
            {{ form.username }}
    
            <label for="id_firstname">First Name</label>
            {{ form.first_name }}
            
            <label for="id_lastname">Last Name</label>
            {{ form.last_name }}   
            
            <label for="id_email">Email</label>
            {{ form.email }}   

            <button type="submit">SAVE CHANGES</button>
        </form>
        </div>

        <div class="cancel-text-container">
            <div><a class="cancel-text" href="{% url 'view-profile' userID=request.user.id %}">CANCEL</a></div>
        </div>
    
        
    </div>

{% endblock %}

base/templates/base/home.html
{% extends 'main.html' %}

{% block content %}
    <div class="main-container">
        {% if user.is_authenticated %}
            <h1 class="hello-user-text">
                PICKS FOR {{ user.first_name|upper }} {{user.last_name|upper }}
            </h1>
            {% else %}
            <h1>
                Welcome, Guest!
            </h1>
        {% endif %}

        {% for blog in blogs %} 
        <div class="blog-card-container">
            <div class="blog-card-image">
                {% if blog.image %}
                <img src="{{ blog.image.url }}" alt="{{ blog.title }}" class="blog-image" />
                {% else %}
                <img src="" alt="{{ blog.title }}" class="blog-image" />
                {% endif %}
            </div>

            <div  class="blog-card-text">
                <div style="display:flex; justify-content: space-between;">
                    <h2 class="blog-title">{{blog.title}}</h2>
                    <p class="blog-likes">❤ {{blog.number_of_likes}}</p>
                </div>
                <p class="author-name">By <a href="{% url 'view-profile' blog.author.id %}">{{blog.author.first_name}} {{blog.author.last_name}}</a></p>
                <p class="content-preview">{{blog.content|truncatechars:350 }}</p>
                <button class="button read"><a href="{% url 'read-blog' blog.id %}">READ MORE</a></button>
                
            </div>
        </div>
        <hr style="opacity: 0.5;">
        {% endfor %}
    </div>

{% endblock %}

base/templates/base/landing_page.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
    <div class="main-container">
        <div class="banner-img-container">
            <img class="banner-image" src="{% static 'banner.png' %}">
        </div>

        <div class="button-container">
            <button class="button landing-button"><a href="{% url 'login' %}">START READING</a></button>
            <button class="button landing-button"><a href="{% url 'login' %}">START CREATING</a></button>
        </div>

        <div class="button-container">
            <div class="line"></div>
            <h1 class="our-readers-loved-text">OUR READERS LOVED</h1>
            <div class="line"></div>
        </div>

        {% for blog in blogs %} 
        <div class="blog-card-container">
            <div class="blog-card-image">
                <img src="{{ blog.image.url }}" alt="{{ blog.title }}" class="blog-image" />
            </div>

            <div  class="blog-card-text">
                <div style="display:flex; justify-content: space-between;">
                    <h2 class="blog-title">{{blog.title}}</h2>
                    <p class="blog-likes">❤ {{blog.number_of_likes}}</p>
                </div>                
                <p class="author-name">By <a href="{% url 'view-profile' blog.author.id %}">{{blog.author.first_name}} {{blog.author.last_name}}</a></p>
                <p class="content-preview">{{blog.content|truncatechars:350 }}</p>
                <button class="button read"><a href="{% url 'read-blog' blog.id %}">READ MORE</a></button>
                
            </div>
        </div>
        <hr style="opacity: 0.5;">
        {% endfor %}

    </div>

{% endblock %}

base/templates/base/login.html
{% extends 'main.html' %}

{% block content %}

<div class="main-container">
    <div class="login-container-1">
        <div class="login-container">
            <h1 class="login-text">LOGIN</h1>
            <form method = "POST" id="login-form">
                {% csrf_token %}
                <input type="text" id="username" name="username" placeholder="Username" >
                <input type="password" id="password" name="password" placeholder="Password" >
                <input type="submit" value = "Login"/>
            </form>
            <p id="error-message" style="color: red;"></p>
            <p class="author-name">Haven't signed up yet?</p>
            <a class ="comment-time" href = "{% url 'register' %}">Sign up</a>
        </div>
    </div>
</div>

{% endblock content %}

base/templates/base/read_blog.html
{% extends 'main.html' %}

{% block content %}

<div class="main-container">
    <div class="blog-title-container">
        <div class="blog-title-box">
            <h1 class="blog-title-text">{{blog.title}}</h1>
            <p class="author-name-text">By <a href="{% url 'view-profile' blog.author.id %}">{{blog.author.username}}</a></p>
        </div>

        <div class="blog-likes-comment">
            <button class="like-button" data-id="{{ blog.id }}">
                {% if request.user in blog.liked_by.all %} Unlike
                {% else %} Like
                {% endif %}
            </button>
            <p class="like-count">{{ blog.number_of_likes }}</p> 
            <p>❤</p>
        </div>

    </div>
    
    <hr class="small-line">
    <div class="content-container">
        <p class="content">{{blog.content|linebreaks }}</p>
    </div>
    <p class="comment-time">Posted {{blog.created_on | timesince }} ago</p>
    <br>
    <h2 class="leave-comment-text">Leave a comment. . . </h2>
          <form method="POST" action="">
              {% csrf_token %}
              <div class="comment-form-container">
                {{ commentform.as_p }}
              </div>
              <input class = "button comment" type="submit" value="Post Comment"/>
          </form>
    <br>

    <div class="comment-container">
        <h2 class="leave-comment-text">Reader Comments</h2>
        {% for comment in comments %}
            <div class="comment-box">
                {% if comment.user == blog.author %}
                <span class="comment-username"><a href="{% url 'view-profile' blog.author.id %}">@{{comment.user.username}}</a> <span class="author-comment">AUTHOR</span></span>
                {% else %}
                <span class="comment-username"><a href="{% url 'view-profile' comment.user.id %}">@{{comment.user.username}}</a></span>
                {% endif %}
                <p class="comment-body">{{comment.body}}</p>
                <p class="comment-time">Posted {{comment.created | timesince }} ago</p>
            </div>   
            {% empty %}
            <p class="no-comments">No comments yet. Be the first to comment!</p> 
        {% endfor %}
    </div>

</div>
<script>
    const csrftoken = '{{ csrf_token }}';
</script>

{% endblock %}

base/templates/base/register.html
{% extends 'main.html' %}

{% block content %}

<div class="main-container">
    <div class="register-container-1">
        <div class="register-container">
            <h1 class="login-text">REGISTER</h1>
            <form method="POST">
                {% csrf_token %}
                <div class="register-field">
                    <label  for="id_username">Username</label>
                    {{ form.username }}
                    <p class="caption-text">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</p>
                </div>

                <div class="register-field">
                    <label for="id_firstname">First Name</label>
                    {{ form.first_name }}
                </div>

                <div class="register-field">
                    <label for="id_lastname">Last Name</label>
                    {{ form.last_name }}
                </div>
                
                <div class="register-field">
                    <label for="id_email">Email</label>
                    {{ form.email }}
                </div>
                
                <div class="register-field">
                    <label for="id_password1">Password</label>
                    {{ form.password1 }}
                    <p class="caption-text">Your password can’t be too similar to your other personal information.</p>
                    <p class="caption-text">Your password must contain at least 8 characters.</p>
                    <p class="caption-text">Your password can’t be a commonly used password.</p>
                    <p class="caption-text">Your password can’t be entirely numeric.</p>
                </div>
                
                <div class="register-field">
                    <label for="id_password2">Confirm Password</label>
                    {{ form.password2 }}
                    <p class="caption-text">Enter the same password as before, for verification.</p>
                </div>

                <input type="submit" value="Register"/>
            </form>
            <p class="author-name">Already signed up?</p>
            <a class ="comment-time" href="{% url 'login' %}">Login</a>
        </div>
    </div>

</div>

{% endblock content %}

base/templates/base/view_profile.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
    <div class="main-container">
        <h1 class="hello-user-text">{{ user_profile.first_name|upper}} {{user_profile.last_name|upper}}'S PROFILE</h1>
        <div class="profile-box">
            <div class="profile-image-container">
                <img class="default-profile-pic" src="{% static 'logo.png' %}">
            </div>
            <div class="profile-details">
                <p class="profile-name">{{ user_profile.first_name }} {{ user_profile.last_name }}</p>
                <p class="profile-username"> @{{ user_profile.username }}</p>
        
                {% if is_owner %}
                    <p class="profile-email">{{ user_profile.email }}</p>
                    <a href="{% url 'edit-profile' %}" class="edit-profile-link">EDIT PROFILE</a>

                {% else %}
                    <p class="profile-email">Joined {{ user_profile.date_joined|timesince }} ago</p>
                    <a href="" class="edit-profile-link">FOLLOW</a>
                    
                {% endif %}
            </div>
        </div>
        <br>
        <h1 class="hello-user-text">BLOGS BY {{ user_profile.first_name|upper}} {{user_profile.last_name|upper}}</h1>
        {% for blog in blogs %}
        <div class="blog-card-container">
            <div class="blog-card-image">
                <img src="{{ blog.image.url }}" alt="{{ blog.title }}" class="blog-image" />
            </div>

            <div  class="blog-card-text">
                <h2 class="blog-title">{{blog.title}}</h2>
                <p class="author-name">By <a href="{% url 'view-profile' blog.author.id %}">{{blog.author.first_name}} {{blog.author.last_name}}</a></p>
                <p class="content-preview">{{blog.content|truncatechars:350 }}</p>
                <button class="button read"><a href="{% url 'read-blog' blog.id %}">READ MORE</a></button>
            </div>
        </div>
        <hr style="opacity: 0.5;">
        {% empty %}
        <p class="no-comments">{{ user_profile.first_name|title}} {{user_profile.last_name|title}} has not written any blogs yet. </p>
        {% endfor %}
    </div>

{% endblock %}

templates/footer.html
{% load static %}
<footer>
    <div class="footer-container">
        <div class="footer-logo">
            <a href=""><img src="{% static 'logo.png' %}" alt="Logo"></a>
        </div>
        
        <div class="footer-links">
            <a href="#about">About</a>
            <a href="#facebook">Facebook</a>
            <a href="#facebook">Instagram</a>
            <a href="#facebook">Twitter</a>
            <a href="#contact">Contact Us</a>
        </div>
        

    </div>
    <div class="footer-bottom">
        &copy; 2024 Aether. All rights reserved.
    </div>
</footer>

templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel="icon" href="{% static 'logo.png' %}" type="image/png">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Baskervville:ital@0;1&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Red+Hat+Display:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@0,8..60,200..900;1,8..60,200..900&display=swap" rel="stylesheet">
    <title>Aether</title>
  </head>

  <body>  
    {% include 'navbar.html' %}

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    
    {% block content %} 

    {% endblock %}
    {% include 'footer.html' %}
    <script src="{% static 'script.js' %}"></script>
      
  </body>

</html>

templates/navbar.html
{% load static %}
<header>
    <nav>
        <ul class="nav-left">
            <li><a href=""><img class="logo-image" src="{% static 'aether.png' %}" alt="Logo"></a></li>
            <li><a href="{% url 'home' %}">EXPLORE</a></li>
	    <li><a href="{% url 'create-blog' %}">WRITE</a></li>
            <li><a href="{% url 'about-us' %}">ABOUT US</a></li>
        </ul>
        <ul class="nav-right">
            {% if request.user.is_authenticated %}
                <li><a href="{% url 'view-profile' userID=request.user.id %}" class="hello-text">Hello, {{user.first_name | title}}</li>
                <li><a href="{% url 'logout' %}"><button class="button register">LOGOUT</button></a></li>
            {% else %}
                <li><a href="{% url 'login' %}"><button class ="button login">LOGIN</button></a></li>
                <li><a href="{% url 'register' %}"><button class ="button register">REGISTER</button></a></li>
            {% endif %}
            
        </ul>
    </nav>
</header>